import { AppState, Phase, Task, Reminder, PMRole, ContestantTask } from './types'

let taskCounter = 0
function makeTask(text: string, owner: '' | 'Kanishkar' | 'Sanskar' | 'Shared', note: string): Task {
  taskCounter++
  return { id: `t${taskCounter}`, text, owner, done: false, note }
}

const RECORDING_CHECKLIST: ContestantTask[] = [
  'Said my name + role to camera at start',
  'Talked to camera before writing my first prompt',
  'Explained my plan to camera (Plan Phase)',
  'Talked to camera when AI did something unexpected',
  'Mid-build check-in: talked to camera at 12:00 PM',
  'Mid-build check-in: talked to camera at 1:00 PM',
  'Mid-build check-in: talked to camera at 2:30 PM',
  'Mid-build check-in: talked to camera at 3:30 PM',
  'Reaction to the Bug Bounty PR (3:00 PM)',
  "Demo'd what I built to camera",
  'Confidence Meter check-in: said my score out loud',
  'Tella TV recording running',
  'Sign-off to camera at end of day',
].map((text, i) => ({ id: `ct${i + 1}`, text, done: false }))

const PHASES: Phase[] = [
  {
    id: 'bf-creative',
    title: '1. BEFORE FRIDAY — Creative & content (Sanskar)',
    time: 'Before Friday',
    group: '1. BEFORE FRIDAY',
    tasks: [
      makeTask('Finalise the build prompt / problem statement', 'Sanskar', ''),
      makeTask('Write the evaluation rubric Chakra will use', 'Sanskar', ''),
      makeTask('Draft Chakra interview questions in 3 levels (easy / medium / hard)', 'Sanskar', 'Per contestant'),
      makeTask('Write and print rules of the challenge (1 large card)', 'Sanskar', 'Host reads on camera'),
      makeTask('Generate Chakra voice samples in ElevenLabs and test playback', 'Sanskar', ''),
      makeTask("Brief yourself on the PM (villain) bit — feedback / can-stacking / code-shipping beats", 'Sanskar', "You're the villain"),
      makeTask('Write skeleton host script + lighting plan per room / production sheet', 'Kanishkar', ''),
      makeTask('Send TellaTV credentials', '', ''),
    ],
  },
  {
    id: 'bf-comms',
    title: '1. BEFORE FRIDAY — Contestant comms & decisions (Shared)',
    time: 'Before Friday',
    group: '1. BEFORE FRIDAY',
    tasks: [
      makeTask('Confirm with each contestant which AI accounts/models they want', 'Sanskar', ''),
      makeTask('Ask each contestant about allergies and dietary preferences', 'Sanskar', ''),
      makeTask('Send each contestant a calm brief: arrival time, dress code, what to bring', 'Sanskar', ''),
      makeTask('Confirm staggered arrival times between 9:30–10:30 AM', 'Sanskar', ''),
      makeTask('Wednesday briefing call — full team together', 'Shared', ''),
      makeTask('Create WhatsApp group with all ADs', 'Kanishkar', ''),
      makeTask('Production Plan finalised and shared', 'Kanishkar', ''),
      makeTask('Call Sheet finalised and shared', 'Kanishkar', 'See dedicated tab — Kanishkar to build before event'),
    ],
  },
  {
    id: 'bf-ai',
    title: '1. BEFORE FRIDAY — AI accounts & tools (Kanishkar)',
    time: 'Before Friday',
    group: '1. BEFORE FRIDAY',
    tasks: [
      makeTask('Buy / provision the required AI accounts — paid plans on contestant logins', 'Sanskar', ''),
      makeTask('Test each login on the actual build machine they\'ll use', 'Sanskar', ''),
      makeTask('Verify token / cost tracking can be pulled live for The Receipt', 'Sanskar', ''),
    ],
  },
  {
    id: 'bf-props',
    title: '1. BEFORE FRIDAY — Props to buy / print (Kanishkar)',
    time: 'Before Friday',
    group: '1. BEFORE FRIDAY',
    tasks: [
      makeTask('Print problem statement (1 sealed envelope per contestant)', 'Sanskar', ''),
      makeTask("Name tags: 'HI my name is Vibe Coder', 'Junior Dev', 'Senior Dev'", 'Sanskar', ''),
      makeTask('Fake moustache for Sanskar (PM character)', 'Sanskar', ''),
      makeTask('PM costume — suit jacket and tie for Sanskar', 'Sanskar', ''),
      makeTask('Optional PM props: clipboard, fake corporate lanyard, big mug', 'Sanskar', ''),
      makeTask("Cans of Diet Coke (for PM 'stack the cans' bit + lifeline)", 'Sanskar', ''),
    ],
  },
  {
    id: 'bf-rooms',
    title: '1. BEFORE FRIDAY — Rooms & studio (Kanishkar)',
    time: 'Before Friday',
    group: '1. BEFORE FRIDAY',
    tasks: [
      makeTask('Book all rooms in calendar', 'Sanskar', ''),
      makeTask("Set up speakers in long meeting room for Chakra's voice", 'Kanishkar', ''),
    ],
  },
  {
    id: 'bf-equipment',
    title: '1. BEFORE FRIDAY — Equipment (Kanishkar)',
    time: 'Before Friday',
    group: '1. BEFORE FRIDAY',
    tasks: [
      makeTask('Confirm and test all camera equipment', 'Kanishkar', ''),
      makeTask('2 roaming cams for build floor', 'Kanishkar', ''),
      makeTask('1 locked-off cam per build station (over-the-shoulder)', 'Kanishkar', ''),
      makeTask('1 cam in Vibe Check room', 'Kanishkar', ''),
      makeTask('1 locked-off cam in Confession Cam booth', 'Kanishkar', ''),
      makeTask('1 cam in Chakra interview room', 'Kanishkar', ''),
      makeTask('Lav mics — one per contestant + host + PM (Sanskar)', 'Kanishkar', ''),
      makeTask('Backup batteries + SD cards for all cameras', 'Kanishkar', ''),
      makeTask('Tella TV / screen recording installed on each build machine', 'Sanskar', 'Split recording every 1 hour'),
      makeTask('Live token/cost tracking dashboard ready (The Receipt)', 'Sanskar', ''),
    ],
  },
  {
    id: 'bf-logistics',
    title: '1. BEFORE FRIDAY — Logistics & people (Kanishkar)',
    time: 'Before Friday',
    group: '1. BEFORE FRIDAY',
    tasks: [
      makeTask("Book Ohshin's return flight", 'Sanskar', ''),
      makeTask('Email building security with names of everyone entering', 'Sanskar', ''),
      makeTask('Order lunch (covering all dietary needs)', 'Sanskar', ''),
      makeTask('Stock fridge with water, energy drinks, Diet Coke', 'Sanskar', ''),
      makeTask('Snacks at each build station (avoid crunchy wrappers — audio)', 'Sanskar', ''),
    ],
  },
  {
    id: 'fm-setup',
    title: '2. FRIDAY MORNING — Before contestants arrive',
    time: '9:00–9:30 AM',
    group: '2. FRIDAY MORNING',
    tasks: [
      makeTask('All cameras powered on, white-balanced, framed', 'Kanishkar', ''),
      makeTask('All build machines logged in, AI accounts open', 'Kanishkar', ''),
      makeTask('Screen recording tested and rolling on every build machine', 'Kanishkar', ''),
      makeTask('Audio check — every lav, every room', 'Kanishkar', ''),
      makeTask('The Receipt tracking system live and verified', 'Kanishkar', ''),
      makeTask("Sanskar in PM costume staged — moustache and suit on standby (don't reveal)", 'Sanskar', ''),
      makeTask('Sealed problem statement envelopes ready', 'Sanskar', ''),
      makeTask('Name tags laid out, ready to hand over on arrival', 'Sanskar', ''),
    ],
  },
  {
    id: 'pre-arrival',
    title: '3. BEFORE ARRIVAL PHASE',
    time: '9:30 AM',
    group: '3. ARRIVAL',
    tasks: [
      makeTask('Vibe Check room camera rolling', 'Kanishkar', ''),
      makeTask('Build floor roaming cams rolling for arrival B-roll', 'Kanishkar', ''),
    ],
  },
  {
    id: 'during-arrival',
    title: '3. DURING ARRIVAL',
    time: '9:30–10:30 AM',
    group: '3. ARRIVAL',
    tasks: [
      makeTask('Hand out name tags — capture B-roll of them putting tags on', 'Kanishkar', ''),
      makeTask('Mic everyone up — lavs ON and recording', 'Kanishkar', ''),
      makeTask('Shoot intros to camera: name / role / years coding', 'Kanishkar', ''),
      makeTask('Capture arrival shots — walking in, sitting down, looking around', 'Kanishkar', ''),
      makeTask('Hype video / Mortal Kombat-style poses for each contestant', 'Kanishkar', ''),
      makeTask('Help each contestant set up at their station', 'Kanishkar', ''),
    ],
  },
  {
    id: 'pre-plan',
    title: '4. BEFORE PLAN PHASE',
    time: '10:30 AM',
    group: '4. PLAN PHASE',
    tasks: [
      makeTask('Vibe Check room set, branded backdrop visible', 'Kanishkar', ''),
      makeTask("Camera rolling in each contestant's room", 'Kanishkar', ''),
      makeTask('Screen recording confirmed on every machine', 'Kanishkar', ''),
      makeTask("Printed rules card in host's hand", 'Sanskar', ''),
      makeTask('3 lifeline cards ready to present', 'Sanskar', ''),
    ],
  },
  {
    id: 'vibe-check',
    title: '4. DURING THE VIBE CHECK (pre-Plan)',
    time: '10:30 AM',
    group: '4. PLAN PHASE',
    tasks: [
      makeTask('Each contestant picks their AI model on camera', 'Sanskar', 'Ask: Which model? Why? What can go wrong?'),
      makeTask('If Claude → ask about the 5-hour rate limits', 'Sanskar', ''),
      makeTask('Capture first Confidence Meter score (1–10)', 'Sanskar', ''),
      makeTask('Ask: Who are you most worried about? What position will you place?', 'Sanskar', ''),
      makeTask('Read the rules out one by one, on camera', 'Sanskar', ''),
      makeTask('Offer the 3 lifelines', 'Sanskar', ''),
    ],
  },
  {
    id: 'during-plan',
    title: '4. DURING PLAN PHASE',
    time: '10:30–11:00 AM',
    group: '4. PLAN PHASE',
    tasks: [
      makeTask('Camera records each contestant the full 30 minutes', 'Kanishkar', ''),
      makeTask("Producer prompts Vibe Coder: 'Are you just starting like this?'", 'Sanskar', ''),
      makeTask('Capture Junior Dev making a CLAUDE.md', 'Kanishkar', ''),
      makeTask('Capture Senior Dev building a SKILLS.md', 'Kanishkar', ''),
      makeTask('Check API/token usage at end of Plan Phase', 'Kanishkar', ''),
      makeTask('Plan Cam piece-to-camera at the end — 90 seconds each', 'Sanskar', ''),
    ],
  },
  {
    id: 'pre-build1',
    title: '5. BEFORE BUILD PHASE 1',
    time: '11:00 AM',
    group: '5. BUILD PHASE 1',
    tasks: [
      makeTask('Bring all contestants back to Vibe Check room', 'Sanskar', ''),
      makeTask('Second Confidence Meter reading on camera', 'Sanskar', ''),
      makeTask('Ask: Who worries you most? What position? Anything going wrong or better?', 'Sanskar', ''),
      makeTask('Confirm model choice for build phase', 'Sanskar', ''),
      makeTask('Two roaming cams ready on the build floor', 'Kanishkar', ''),
      makeTask('Screen captures rolling on every machine', 'Kanishkar', ''),
      makeTask('Host commentary mic separate and recording', 'Kanishkar', ''),
    ],
  },
  {
    id: 'during-build1',
    title: '5. DURING BUILD PHASE 1',
    time: '11:00 AM – 1:30 PM',
    group: '5. BUILD PHASE 1',
    tasks: [
      makeTask('Quick on-cam check-ins at 12:00 PM and 1:00 PM', 'Sanskar', ''),
      makeTask('Encourage contestants to talk to camera about AI wins/fails', 'Sanskar', ''),
      makeTask('Check token usage every 30 minutes (for The Receipt)', 'Kanishkar', ''),
    ],
  },
  {
    id: 'pm-round',
    title: '5. PM ROUND — Sanskar enters in costume',
    time: 'During Build Phase 1',
    group: '5. BUILD PHASE 1',
    tasks: [
      makeTask('Give one contestant 15 minutes of pointless feedback', 'Sanskar', ''),
      makeTask("Tell another to stack Diet Coke cans 'because it talks about architecture'", 'Sanskar', ''),
      makeTask('Sit with the third and start shipping code — helpful but disruptive', 'Sanskar', ''),
    ],
  },
  {
    id: 'pre-lunch',
    title: '6. BEFORE LUNCH',
    time: '1:30 PM',
    group: '6. LUNCH',
    tasks: [
      makeTask('Lunch confirmed delivered, allergies respected', 'Kanishkar', ''),
      makeTask('Camera rolling for casual lunch B-roll', 'Kanishkar', ''),
      makeTask('Crew break scheduled and communicated', 'Kanishkar', ''),
    ],
  },
  {
    id: 'pre-build2',
    title: '7. BEFORE BUILD PHASE 2',
    time: '2:00 PM',
    group: '7. BUILD PHASE 2',
    tasks: [
      makeTask('All contestants back at stations', 'Kanishkar', ''),
      makeTask('Screen recording resumed on every machine', 'Kanishkar', ''),
      makeTask('Bug Bounty PR ready to drop at 3:00 PM', 'Sanskar', ''),
      makeTask('Countdown timer / clock prepared for final stretch', 'Kanishkar', ''),
    ],
  },
  {
    id: 'during-build2',
    title: '7. DURING BUILD PHASE 2',
    time: '2:00–4:00 PM',
    group: '7. BUILD PHASE 2',
    tasks: [
      makeTask('On-cam check-ins at 2:30 PM and 3:30 PM', 'Sanskar', ''),
      makeTask('3:00 PM — host PRs pre-written Bug Bounty bug into each repo', 'Sanskar', ''),
      makeTask('Capture any lifeline usage on camera', 'Kanishkar', ''),
      makeTask('Towards the end — visible countdown, ramp the urgency', 'Sanskar', ''),
    ],
  },
  {
    id: 'pre-demos',
    title: '8. BEFORE THE DEMOS',
    time: '4:00 PM',
    group: '8. DEMOS',
    tasks: [
      makeTask('Crew reset — Vibe Check room ready', 'Kanishkar', ''),
      makeTask('Clean screen recording set up for each demo', 'Kanishkar', ''),
      makeTask('Reaction cam ready for opponents watching the demo', 'Kanishkar', ''),
    ],
  },
  {
    id: 'during-demos',
    title: '8. DURING THE DEMOS',
    time: '4:00 PM',
    group: '8. DEMOS',
    tasks: [
      makeTask('Final Confidence Meter score from each contestant', 'Sanskar', ''),
      makeTask('Show what they built, which test cases passed', 'Sanskar', ''),
      makeTask('Ask: Any regrets? Model choice? Lifeline?', 'Sanskar', ''),
    ],
  },
  {
    id: 'pre-interview',
    title: '9. BEFORE CHAKRA INTERVIEW',
    time: '4:30 PM',
    group: '9. CHAKRA INTERVIEW',
    tasks: [
      makeTask('Feed Chakra: codebase + prompt history + final website for each contestant', 'Sanskar', ''),
      makeTask('3-level interview questions queued (easy / medium / hard)', 'Sanskar', ''),
      makeTask("Sanskar's laptop set up in long meeting room with speakers", 'Kanishkar', ''),
      makeTask('Camera and clean audio rolling in interview room', 'Kanishkar', ''),
      makeTask('FLAG: confirm interview length — 30 min vs 10 min × 3 parallel', 'Sanskar', 'Open question to resolve'),
    ],
  },
  {
    id: 'during-interview',
    title: '9. DURING THE INTERVIEW',
    time: '4:30 PM',
    group: '9. CHAKRA INTERVIEW',
    tasks: [
      makeTask('Capture every interview on camera', 'Kanishkar', ''),
      makeTask("Capture each contestant's reaction immediately after their interview", 'Sanskar', ''),
      makeTask('Get one positive + one piece of feedback about Chakra from each', 'Sanskar', ''),
      makeTask('Capture any jokes about the interviewer', 'Sanskar', ''),
    ],
  },
  {
    id: 'pre-announce',
    title: '10. BEFORE WINNER ANNOUNCEMENT',
    time: '5:00 PM',
    group: '10. WINNER ANNOUNCEMENT',
    tasks: [
      makeTask('Feed meeting transcript into Claude → ask for winner + reasoning', 'Sanskar', ''),
      makeTask("Generate Chakra's announcement voice line in ElevenLabs", 'Sanskar', ''),
      makeTask('Over-the-shoulder shot of laptop in collab area set up', 'Kanishkar', ''),
      makeTask('All three contestants in frame for the wide shot', 'Kanishkar', ''),
    ],
  },
  {
    id: 'during-announce',
    title: '10. DURING THE ANNOUNCEMENT',
    time: '5:00 PM',
    group: '10. WINNER ANNOUNCEMENT',
    tasks: [
      makeTask('Chakra announces the result via ElevenLabs voice', 'Sanskar', ''),
      makeTask('One good thing + one bad thing said about each contestant before reveal', 'Sanskar', ''),
      makeTask('Host closing monologue — multiple takes', 'Sanskar', ''),
      makeTask('Capture contestant reactions live and again as pickups', 'Kanishkar', ''),
      makeTask('2 lines from the winner themselves', 'Sanskar', ''),
    ],
  },
  {
    id: 'before-wrap',
    title: '11. BEFORE WRAP',
    time: '6:30 PM',
    group: '11. WRAP',
    tasks: [
      makeTask('Exit interview with each contestant', 'Sanskar', ''),
      makeTask('Sign-off to camera from each contestant', 'Sanskar', ''),
      makeTask('Final B-roll pass — see Shot List tab', 'Kanishkar', ''),
      makeTask('Back up all footage to drives before crew leaves', 'Kanishkar', ''),
    ],
  },
]

const REMINDERS: Reminder[] = [
  {
    id: 'r1',
    text: 'Screenshot token usage on each machine. File as: vibe-HHMM, junior-HHMM, senior-HHMM',
    time: '11:30',
    fired: false,
    repeatMinutes: 30,
    repeatUntil: '16:00',
  },
  { id: 'r2', text: 'PM enters in 5 minutes — Sanskar get in costume', time: '11:55', fired: false },
  { id: 'r3', text: 'Mid-Build 1 check-in on camera', time: '12:00', fired: false },
  { id: 'r4', text: '1:00 PM Build 1 check-in on camera', time: '13:00', fired: false },
  {
    id: 'r5',
    text: 'Build Phase 1 ending in 5 minutes',
    time: '13:25',
    fired: false,
    broadcastToContestants: true,
  },
  {
    id: 'r6',
    text: 'Lunch break — pause timers',
    time: '13:30',
    fired: false,
    broadcastToContestants: true,
  },
  {
    id: 'r7',
    text: 'Resume timers — Build Phase 2 starts now',
    time: '14:00',
    fired: false,
    broadcastToContestants: true,
  },
  { id: 'r8', text: '2:30 PM Build 2 check-in on camera', time: '14:30', fired: false },
  { id: 'r9', text: 'Drop the Bug Bounty PR into each repo NOW', time: '15:00', fired: false },
  { id: 'r10', text: '3:30 PM Build 2 check-in on camera', time: '15:30', fired: false },
  { id: 'r11', text: '10 min left — ramp the countdown', time: '15:50', fired: false },
  {
    id: 'r12',
    text: 'Build Phase 2 ending in 5 minutes',
    time: '15:55',
    fired: false,
    broadcastToContestants: true,
  },
  { id: 'r13', text: 'Demos start — final Confidence Meter', time: '16:00', fired: false },
  { id: 'r14', text: 'Chakra interview prep — feed it the codebases', time: '16:30', fired: false },
  { id: 'r15', text: 'Winner monologue — multiple takes', time: '17:00', fired: false },
]

const PM_ROLES: PMRole[] = [
  {
    label: 'Contestant 1 — pointless feedback',
    text: "Pull up a chair. Ask what their architecture is. Nod thoughtfully. Suggest renaming a variable. Question why they didn't use microservices. Talk about scalability for 15 minutes. Walk away without resolving anything.",
  },
  {
    label: 'Contestant 2 — stack the Diet Cokes',
    text: "Tell them you need to see their 'systems thinking' demonstrated physically. Hand them Diet Coke cans. Tell them to stack them in a pyramid. When they ask why, say: 'it's about architecture.' Watch them do it.",
  },
  {
    label: 'Contestant 3 — helpful but disruptive',
    text: "Sit down at their machine. Start writing actual code that works but isn't what they were doing. Push commits. Refuse to leave. When they protest, say you're 'just trying to help unblock you.'",
  },
]

export function getSeedState(): AppState {
  taskCounter = 0
  return {
    phases: PHASES,
    reminders: REMINDERS,
    pmRoles: PM_ROLES,
    timers: {
      vibe: { elapsed: 0, running: false, startedAt: null },
      junior: { elapsed: 0, running: false, startedAt: null },
      senior: { elapsed: 0, running: false, startedAt: null },
    },
    notifications: [],
    pauseRequests: [],
    contestantNotes: { vibe: '', junior: '', senior: '' },
    contestantChecklists: {
      vibe: RECORDING_CHECKLIST.map(t => ({ ...t, id: `vibe-${t.id}` })),
      junior: RECORDING_CHECKLIST.map(t => ({ ...t, id: `junior-${t.id}` })),
      senior: RECORDING_CHECKLIST.map(t => ({ ...t, id: `senior-${t.id}` })),
    },
  }
}
